version: '3.3'

services:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: ${IMAGE:-pipservices/app}
    links:
      - email
    environment:
      - HTTP_ENABLED=true
      - GRPC_ENABLED=true
      - EMAIL_SERVICE_HOST=email
      - EMAIL_SERVICE_PORT=8080
    ports:
      - "8080:8080"
      - "8090:8090"

  email:
    image: pipservices/service-email-node:1.1.0-17
    environment:
      - HTTP_ENABLED=true
      - GRPC_ENABLED=true
